// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEEpC-yQsWQv2TiqWAkNN_utcp7TvphQ',
    appId: '1:1096443926227:android:27ab76ac6a6f5145ece626',
    messagingSenderId: '1096443926227',
    projectId: 'nutri-app-28ff6',
    storageBucket: 'nutri-app-28ff6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp6VvKPkmdqxNSd--TYbfbNp98GmDVoeU',
    appId: '1:1096443926227:ios:29712a007a682f95ece626',
    messagingSenderId: '1096443926227',
    projectId: 'nutri-app-28ff6',
    storageBucket: 'nutri-app-28ff6.firebasestorage.app',
    androidClientId: '1096443926227-16be3akcjpfi6m0fhh1j1csprgv84a1u.apps.googleusercontent.com',
    iosClientId: '1096443926227-i9jeq9m20gtkktvfgke6hfbl069iqeab.apps.googleusercontent.com',
    iosBundleId: 'com.ahara.ahara',
  );
}
